check_start_end <- function(st, en, m) {
  posix <- c("POSIXct", "POSIXt")
  if(!is(st, posix) | !is(en, posix)) {
    stop(m)
  }
}
#' Create ical object using character dates
#'
#' @param start_time start as character
#' @param end_time end as character
#' @param summary short outline of the event
#' @param format strptime format
#' @return object of class ics
#' @export
#' @examples
#' ic_event_raw()
ic_event_raw <- function(
  start_time = "20180927 13:00",
  end_time = "20180927 15:00",
  summary = "R ical minihack",
  format = "%Y%m%d %H:%M") {
  # TODO: supprress as.POSIXct warnings replace with ical checks.
  st <- as.POSIXct(start_time, format = format)
  en <- as.POSIXct(end_time, format = format)
  # m <- paste0("ical failed to validate dates or format is not matching/missing try: ic_event_row(",
  #             start_time, ", ", end_time, ", format = ical::formats$PICK")
  # if(identical(class(st), "try-error") | identical(class(en), "try-error")) {
  #   warning(m)
  # }

  if(identical(start_time, "20180927 13:00") |
     identical(end_time, "20180927 15:00")) {
    warning("Did you want to use ical default values? start: ", start_time, ", end: ", end_time)
  }
  m <- "ic_event_raw requires both start and end time to be valid character date(time) values."
  check_start_end(st, en, m)
  ic_event(start_time = st, end_time = en, summary = summary)
}

#' Create ical object from properties_core inputs
#' @param uid the unique id of the event, by default generated by `ic_uid()`
#' @param start_time start time, by default the current time to the nearest hour
#' @param end_time end time, by defult and hour (3600 seconds) after `start_time`
#' @param summary short outline of the event
#' @param more_properties add placeholder columns for properties in addition to `properties_core`,
#' dy default `FALSE`
#' @param event_properties named vector of additional properties to include, by default
#' with names `ical::properties` containing `NA`s to be subsequently populated
#' @return object of class ics
#' @export
#' @examples
#' ic_event()
#' ic_event(more_properties = TRUE)
ic_event <- function(
  uid = ic_guid(),
  start_time = as.POSIXct(round.POSIXt(Sys.time(), units = "hours")),
  end_time = as.POSIXct(round.POSIXt(Sys.time(), units = "hours") + 1 * 60 * 60),
  summary = "ical event",

  more_properties = FALSE,
  event_properties = stats::setNames(
    rep(
      NA,
      length(setdiff(ical::properties, ical::properties_core))),
    nm = setdiff(ical::properties, ical::properties_core))) {
  # inputs
  m <- "ic_event requires both start and end time to be valid Sys.time objects."
  check_start_end(start_time, end_time, m)
  if(is.na(summary) | summary == "NA") {
    summary <- "ical event"
  }
  st <- ic_char_datetime(start_time)
  en <- ic_char_datetime(end_time)
  event_values <- c(uid, st, en, summary)
  # TODO: add DTSART and DTEND TZID types
  event <- paste(ical::properties_core, event_values, sep = ":")
  if(more_properties) {
    the_rest <- paste(names(event_properties), event_properties, sep = ":")
  } else {
    the_rest = NULL
  }
  ical(
    c(ical::properties_ical,
      "BEGIN:VEVENT",
      event,
      the_rest,
      "END:VEVENT",
      "END:VCALENDAR"
    )
  )
}


#' Get an ical GUID
#'
#' Provided without any testing. Slight improvement from
#' [SO question](https://stackoverflow.com/a/10493590/2332101)
#' @examples
#' ic_guid()
#' @export
ic_guid <- function() {
  baseuuid <- paste(sample(c(letters[1:6],0:9),30,replace=TRUE),collapse="")
  paste(
    "ical-",
    substr(baseuuid,1,8),
    "-",
    substr(baseuuid,9,12),
    "-",
    "4",
    substr(baseuuid,13,15),
    "-",
    sample(c("8","9","a","b"),1),
    substr(baseuuid,16,18),
    "-",
    substr(baseuuid,19,30),
    sep="",
    collapse=""
  )
}
