#' Create ical object from properties_core inputs
#'
#' Create an ical event using either POSIXct type or character type with format parameters.
#'
#' @param uid the unique id of the event, by default generated by `ic_uid()`
#' @param start_time start time, by default the current time to the nearest hour
#' @param end_time end time, by defult and hour (3600 seconds) after `start_time`
#' @param format required if start_time and end_time are vectors and are not of datetime format
#' "\%Y-\%m-\%d \%H:\%M", you can use `ical::formats` object for convenience.
#' @param summary short outline of the event
#' @param more_properties add placeholder columns for properties in addition to `properties_core`,
#' dy default `FALSE`
#' @param event_properties named vector of additional properties to include, by default
#' with names `ical::properties` containing `NA`s to be subsequently populated
#' @format in case of start_time and end_time being character values, a format must be provided.
#'
#' @return object of class ics
#' @export
#' @examples
#' ic_event()
#' ic_event(more_properties = TRUE)
#' ic_event(start_time = "18-10-12", end_time = "18-10-13", format = ical::formats$`yy-mm-dd`)
ic_event <- function(
  uid = ic_guid(),
  start_time = as.POSIXct(round.POSIXt(Sys.time(), units = "hours")),
  end_time = as.POSIXct(round.POSIXt(Sys.time(), units = "hours") + 1L * 60L * 60L),
  format = "%Y-%m-%d %H:%M",
  summary = "ical event",
  more_properties = FALSE,
  event_properties = ical::properties) {
  posixct <- "POSIXct"
  # inputs
  if(is.na(summary) | summary == "NA") {
    summary <- "ical event"
  }
  st <- start_time
  en <- end_time
  # TODO: mix and match start = Sys.time() finish = "2018-10-12 15" and a format.
  are.posixct <- is(st, posixct) & is(en, posixct)
  are.vectors <- is.vector(st) & is.vector(en)
  if(are.posixct | are.vectors) {
    if(are.vectors) {
      st <- as.POSIXct(st, format = format)
      en <- as.POSIXct(en, format = format)
      # TODO: supprress as.POSIXct warnings replace with ical checks for valid character/raw text.
      # m <- paste0("ical failed to validate dates or format is not matching/missing try: ic_event_row(",
      #             start_time, ", ", end_time, ", format = ical::formats$PICK")
      # if(identical(class(st), "try-error") | identical(class(en), "try-error")) {
      #   warning(m)
      # }
    }
  } else {
    stop("Current version only accepts two identical typed start and end dates.")
  }

  st <- ic_char_datetime(st)
  en <- ic_char_datetime(en)
  event_values <- c(uid, st, en, summary)
  # TODO: add DTSART and DTEND TZID types
  if(identical(event_properties, ical::properties)) {
    # just moving this out of the method signature.
    stats::setNames(
      rep(
        NA,
        length(setdiff(ical::properties, ical::properties_core))),
      nm = setdiff(ical::properties, ical::properties_core))
  }
  event <- paste(ical::properties_core, event_values, sep = ":")
  if(more_properties) {
    the_rest <- paste(names(event_properties), event_properties, sep = ":")
  } else {
    the_rest = NULL
  }
  ical(
    c(ical::properties_ical,
      "BEGIN:VEVENT",
      event,
      the_rest,
      "END:VEVENT",
      "END:VCALENDAR"
    )
  )
}


#' Get an ical GUID
#'
#' Provided without any testing. Slight improvement from
#' [SO question](https://stackoverflow.com/a/10493590/2332101)
#' @examples
#' ic_guid()
#' @export
ic_guid <- function() {
  baseuuid <- paste(sample(c(letters[1:6],0:9),30,replace=TRUE),collapse="")
  paste(
    "ical-",
    substr(baseuuid,1,8),
    "-",
    substr(baseuuid,9,12),
    "-",
    "4",
    substr(baseuuid,13,15),
    "-",
    sample(c("8","9","a","b"),1),
    substr(baseuuid,16,18),
    "-",
    substr(baseuuid,19,30),
    sep="",
    collapse=""
  )
}
